/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as LayoutRouteImport } from './app/routes/_layout'
import { Route as LayoutIndexRouteImport } from './app/routes/_layout.index'
import { Route as LayoutSettingsRouteImport } from './app/routes/_layout.settings'
import { Route as LayoutSearchRouteImport } from './app/routes/_layout.search'
import { Route as LayoutRoomsRouteImport } from './app/routes/_layout.rooms'
import { Route as LayoutNotificationsRouteImport } from './app/routes/_layout.notifications'
import { Route as LayoutMessagesRouteImport } from './app/routes/_layout.messages'
import { Route as LayoutExploreRouteImport } from './app/routes/_layout.explore'
import { Route as LayoutBookmarksRouteImport } from './app/routes/_layout.bookmarks'
import { Route as authRegisterRouteImport } from './app/routes/(auth).register'
import { Route as authLoginRouteImport } from './app/routes/(auth).login'
import { Route as LayoutRoomsIdRouteImport } from './app/routes/_layout.rooms.$id'
import { Route as LayoutProfileUsernameRouteImport } from './app/routes/_layout.profile.$username'
import { Route as LayoutPostIdRouteImport } from './app/routes/_layout.post.$id'
import { Route as LayoutMessagesIdRouteImport } from './app/routes/_layout.messages.$id'
import { Route as LayoutHashtagTagRouteImport } from './app/routes/_layout.hashtag.$tag'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSearchRoute = LayoutSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRoomsRoute = LayoutRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNotificationsRoute = LayoutNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMessagesRoute = LayoutMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExploreRoute = LayoutExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBookmarksRoute = LayoutBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => LayoutRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoomsIdRoute = LayoutRoomsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LayoutRoomsRoute,
} as any)
const LayoutProfileUsernameRoute = LayoutProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPostIdRoute = LayoutPostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMessagesIdRoute = LayoutMessagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LayoutMessagesRoute,
} as any)
const LayoutHashtagTagRoute = LayoutHashtagTagRouteImport.update({
  id: '/hashtag/$tag',
  path: '/hashtag/$tag',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/bookmarks': typeof LayoutBookmarksRoute
  '/explore': typeof LayoutExploreRoute
  '/messages': typeof LayoutMessagesRouteWithChildren
  '/notifications': typeof LayoutNotificationsRoute
  '/rooms': typeof LayoutRoomsRouteWithChildren
  '/search': typeof LayoutSearchRoute
  '/settings': typeof LayoutSettingsRoute
  '/hashtag/$tag': typeof LayoutHashtagTagRoute
  '/messages/$id': typeof LayoutMessagesIdRoute
  '/post/$id': typeof LayoutPostIdRoute
  '/profile/$username': typeof LayoutProfileUsernameRoute
  '/rooms/$id': typeof LayoutRoomsIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/bookmarks': typeof LayoutBookmarksRoute
  '/explore': typeof LayoutExploreRoute
  '/messages': typeof LayoutMessagesRouteWithChildren
  '/notifications': typeof LayoutNotificationsRoute
  '/rooms': typeof LayoutRoomsRouteWithChildren
  '/search': typeof LayoutSearchRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/hashtag/$tag': typeof LayoutHashtagTagRoute
  '/messages/$id': typeof LayoutMessagesIdRoute
  '/post/$id': typeof LayoutPostIdRoute
  '/profile/$username': typeof LayoutProfileUsernameRoute
  '/rooms/$id': typeof LayoutRoomsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/_layout/bookmarks': typeof LayoutBookmarksRoute
  '/_layout/explore': typeof LayoutExploreRoute
  '/_layout/messages': typeof LayoutMessagesRouteWithChildren
  '/_layout/notifications': typeof LayoutNotificationsRoute
  '/_layout/rooms': typeof LayoutRoomsRouteWithChildren
  '/_layout/search': typeof LayoutSearchRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/hashtag/$tag': typeof LayoutHashtagTagRoute
  '/_layout/messages/$id': typeof LayoutMessagesIdRoute
  '/_layout/post/$id': typeof LayoutPostIdRoute
  '/_layout/profile/$username': typeof LayoutProfileUsernameRoute
  '/_layout/rooms/$id': typeof LayoutRoomsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/bookmarks'
    | '/explore'
    | '/messages'
    | '/notifications'
    | '/rooms'
    | '/search'
    | '/settings'
    | '/hashtag/$tag'
    | '/messages/$id'
    | '/post/$id'
    | '/profile/$username'
    | '/rooms/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/bookmarks'
    | '/explore'
    | '/messages'
    | '/notifications'
    | '/rooms'
    | '/search'
    | '/settings'
    | '/'
    | '/hashtag/$tag'
    | '/messages/$id'
    | '/post/$id'
    | '/profile/$username'
    | '/rooms/$id'
  id:
    | '__root__'
    | '/_layout'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/_layout/bookmarks'
    | '/_layout/explore'
    | '/_layout/messages'
    | '/_layout/notifications'
    | '/_layout/rooms'
    | '/_layout/search'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/hashtag/$tag'
    | '/_layout/messages/$id'
    | '/_layout/post/$id'
    | '/_layout/profile/$username'
    | '/_layout/rooms/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/search': {
      id: '/_layout/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof LayoutSearchRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/rooms': {
      id: '/_layout/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof LayoutRoomsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/notifications': {
      id: '/_layout/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof LayoutNotificationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/messages': {
      id: '/_layout/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof LayoutMessagesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/explore': {
      id: '/_layout/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof LayoutExploreRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/bookmarks': {
      id: '/_layout/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof LayoutBookmarksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/rooms/$id': {
      id: '/_layout/rooms/$id'
      path: '/$id'
      fullPath: '/rooms/$id'
      preLoaderRoute: typeof LayoutRoomsIdRouteImport
      parentRoute: typeof LayoutRoomsRoute
    }
    '/_layout/profile/$username': {
      id: '/_layout/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof LayoutProfileUsernameRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/post/$id': {
      id: '/_layout/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof LayoutPostIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/messages/$id': {
      id: '/_layout/messages/$id'
      path: '/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof LayoutMessagesIdRouteImport
      parentRoute: typeof LayoutMessagesRoute
    }
    '/_layout/hashtag/$tag': {
      id: '/_layout/hashtag/$tag'
      path: '/hashtag/$tag'
      fullPath: '/hashtag/$tag'
      preLoaderRoute: typeof LayoutHashtagTagRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutMessagesRouteChildren {
  LayoutMessagesIdRoute: typeof LayoutMessagesIdRoute
}

const LayoutMessagesRouteChildren: LayoutMessagesRouteChildren = {
  LayoutMessagesIdRoute: LayoutMessagesIdRoute,
}

const LayoutMessagesRouteWithChildren = LayoutMessagesRoute._addFileChildren(
  LayoutMessagesRouteChildren,
)

interface LayoutRoomsRouteChildren {
  LayoutRoomsIdRoute: typeof LayoutRoomsIdRoute
}

const LayoutRoomsRouteChildren: LayoutRoomsRouteChildren = {
  LayoutRoomsIdRoute: LayoutRoomsIdRoute,
}

const LayoutRoomsRouteWithChildren = LayoutRoomsRoute._addFileChildren(
  LayoutRoomsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutBookmarksRoute: typeof LayoutBookmarksRoute
  LayoutExploreRoute: typeof LayoutExploreRoute
  LayoutMessagesRoute: typeof LayoutMessagesRouteWithChildren
  LayoutNotificationsRoute: typeof LayoutNotificationsRoute
  LayoutRoomsRoute: typeof LayoutRoomsRouteWithChildren
  LayoutSearchRoute: typeof LayoutSearchRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutHashtagTagRoute: typeof LayoutHashtagTagRoute
  LayoutPostIdRoute: typeof LayoutPostIdRoute
  LayoutProfileUsernameRoute: typeof LayoutProfileUsernameRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutBookmarksRoute: LayoutBookmarksRoute,
  LayoutExploreRoute: LayoutExploreRoute,
  LayoutMessagesRoute: LayoutMessagesRouteWithChildren,
  LayoutNotificationsRoute: LayoutNotificationsRoute,
  LayoutRoomsRoute: LayoutRoomsRouteWithChildren,
  LayoutSearchRoute: LayoutSearchRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutHashtagTagRoute: LayoutHashtagTagRoute,
  LayoutPostIdRoute: LayoutPostIdRoute,
  LayoutProfileUsernameRoute: LayoutProfileUsernameRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
